fix: add support for standalone
webdriverio/visual-testing pull request #219
Opened 2024-02-17 23:16 UTC by wswebcreation

This PR adds support for standalone

It can now be used like this

```ts
import { remote } from 'webdriverio'
import VisualService from '@wdio/visual-service'

let visualService = new VisualService({
    autoSaveBaseline: true
})

const browser = await remote({
    logLevel: 'silent',
    capabilities: {
        browserName: 'firefox',
    }
})

visualService.remoteSetup(browser)

await browser.url('https://webdriver.io/')

await browser.checkScreen('examplePaged', {})

await browser.deleteSession()
```

2024-02-20 02:12 UTC, christian-bromann requested changes
Some comments. Let's just use the `@wdio/globals` primitives here.

2024-02-20 02:12 UTC, christian-bromann commented on packages/service/src/service.ts
> +console.log('globalThis = ', globalThis._wdioGlobals)
```suggestion
```

2024-02-20 02:12 UTC, christian-bromann commented on packages/service/src/service.ts
> +const globals: Map<SupportedGlobals, any> = globalThis._wdioGlobals = globalThis._wdioGlobals || new Map()
Instead of this, can we just use the `@wdio/globals` package here?

2024-02-20 02:12 UTC, christian-bromann commented on packages/service/src/service.ts
> +        console.log('globals', globals)
```suggestion
```

2024-02-21 15:00 UTC, wswebcreation commented
Hi @christian-bromann 

Thanks for the feedback, I've changed it, wdyt now?

2024-02-21 15:41 UTC, christian-bromann approved these changes
LGTM 👍

2024-02-21 16:14 UTC, merged

2024-02-21 16:15 UTC, christian-bromann commented
> Will create the PR on V8 and then do the same for V9 (unless we have a simple way to do that)

That's the right way, thanks!